### ISSUE TITLE
ID conflict

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/dita-refactoring-examples#1]
Following this

https://github.com/oxygenxml/dita-refactoring-examples/blob/5e4e8aec49899292bd00090f48816a1cd72254ad/README.md#L7

and invoking **XML Refactoring** wizard generates this error:

> System ID: ...\29 Terms to abbreviated-forms\termToAbbrev.xml
> Severity: error
> Description: Operation 'Convert terms to abbreviated forms' could not be loaded because there is already an operation 'Set navtitle from topic title' with the same ID: 'Set navtitle from topic title'.

**Comment by raducoravu** [comment]
I fixed the problem by assigning unique IDs to the two operations.
