### ISSUE TITLE
phkeyrefToKeyword.xml name

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/dita-refactoring-examples#2]
https://github.com/oxygenxml/dita-refactoring-examples/blob/c6a219774962e559e16597082952bec466a6e017/25%20Convert%20ph%20keyref%20to%20keyword/phkeyrefToKeyword.xml#L4-L5

`@name` and `<description>` do not seem to match.

**Comment by raducoravu** [comment]
Thanks @AirQuick
