### ISSUE TITLE
ID conflict `convert-attribute-to-element`

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/dita-refactoring-examples#3]
Loading this repository on Oxygen 22.1 build 2020100710 errors out with this message:

> Operation 'Convert attribute to element' could not be loaded because there is already an operation 'Convert attribute to element' with the same ID: 'convert-attribute-to-element'.

Probably it conflicts with one of the built-in operations?
It would be nice if this repository could avoid the conflict.

**Comment by raducoravu** [comment]
Thanks @AirQuick
