### ISSUE TITLE
Cannot check out "35 Remove Done Comments:Changes"

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/dita-refactoring-examples#5]
Trying to check out the latest `master` on Windows fails:

```console
error: invalid path '35 Remove Done Comments:Changes/removeDoneChanges.xml'
error: invalid path '35 Remove Done Comments:Changes/removeDoneChanges.xsl'
```

Looks like `:` isn't acceptable.
Can you consider removing it?

**Comment by raducoravu** [comment]
I just renamed it to "35 Remove Done Comments or Changes", I hope it works now. Thanks for the feedback. I'm working on Mac and I did not test this on Windows.

**Comment by AirQuick** [comment]
It works now. Thanks!
